// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForInsertFlats implements pgx.CopyFromSource.
type iteratorForInsertFlats struct {
	rows                 []InsertFlatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertFlats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertFlats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FlatNumber,
		r.rows[0].HouseID,
	}, nil
}

func (r iteratorForInsertFlats) Err() error {
	return nil
}

func (q *Queries) InsertFlats(ctx context.Context, arg []InsertFlatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"flat"}, []string{"flat_number", "house_id"}, &iteratorForInsertFlats{rows: arg})
}
