// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flat_owner.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertFlatOwner = `-- name: InsertFlatOwner :one
INSERT INTO flat_owner(flat_id, resident_id)
values($1, $2)
RETURNING flat_owner_id, flat_id, resident_id, owner_up_to
`

type InsertFlatOwnerParams struct {
	FlatID     uuid.UUID
	ResidentID uuid.UUID
}

func (q *Queries) InsertFlatOwner(ctx context.Context, arg InsertFlatOwnerParams) (FlatOwner, error) {
	row := q.db.QueryRow(ctx, insertFlatOwner, arg.FlatID, arg.ResidentID)
	var i FlatOwner
	err := row.Scan(
		&i.FlatOwnerID,
		&i.FlatID,
		&i.ResidentID,
		&i.OwnerUpTo,
	)
	return i, err
}
