// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flat.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const flatNumberExistsInHouse = `-- name: FlatNumberExistsInHouse :one
select exists (
  select 1 from flat
  where flat_number = $1
  and house_id = $2
)
`

type FlatNumberExistsInHouseParams struct {
	FlatNumber int32
	HouseID    uuid.UUID
}

func (q *Queries) FlatNumberExistsInHouse(ctx context.Context, arg FlatNumberExistsInHouseParams) (bool, error) {
	row := q.db.QueryRow(ctx, flatNumberExistsInHouse, arg.FlatNumber, arg.HouseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFlatByID = `-- name: GetFlatByID :one
select f.flat_id, f.flat_number, f.house_id, f.area, r.resident_id, r.flat_id, r.phone_number, r.fio from flat f
inner join flat_owner fo on f.flat_id = fo.flat_id
inner join resident r on fo.resident_id = r.resident_id
where f.flat_id = $1
and fo.owner_up_to is null
`

type GetFlatByIDRow struct {
	Flat     Flat
	Resident Resident
}

func (q *Queries) GetFlatByID(ctx context.Context, flatID uuid.UUID) (GetFlatByIDRow, error) {
	row := q.db.QueryRow(ctx, getFlatByID, flatID)
	var i GetFlatByIDRow
	err := row.Scan(
		&i.Flat.FlatID,
		&i.Flat.FlatNumber,
		&i.Flat.HouseID,
		&i.Flat.Area,
		&i.Resident.ResidentID,
		&i.Resident.FlatID,
		&i.Resident.PhoneNumber,
		&i.Resident.Fio,
	)
	return i, err
}

const getFlatWithNumber = `-- name: GetFlatWithNumber :one
select flat_id, flat_number, house_id, area from flat
where flat_number = $1
and house_id = $2
`

type GetFlatWithNumberParams struct {
	FlatNumber int32
	HouseID    uuid.UUID
}

func (q *Queries) GetFlatWithNumber(ctx context.Context, arg GetFlatWithNumberParams) (Flat, error) {
	row := q.db.QueryRow(ctx, getFlatWithNumber, arg.FlatNumber, arg.HouseID)
	var i Flat
	err := row.Scan(
		&i.FlatID,
		&i.FlatNumber,
		&i.HouseID,
		&i.Area,
	)
	return i, err
}

const getFlatsForHouse = `-- name: GetFlatsForHouse :many
select f.flat_id, f.flat_number, f.house_id, f.area, r.resident_id, r.flat_id, r.phone_number, r.fio from flat f
inner join flat_owner fo on f.flat_id = fo.flat_id
inner join resident r on fo.resident_id = r.resident_id
where house_id = $1
and fo.owner_up_to is null
`

type GetFlatsForHouseRow struct {
	Flat     Flat
	Resident Resident
}

func (q *Queries) GetFlatsForHouse(ctx context.Context, houseID uuid.UUID) ([]GetFlatsForHouseRow, error) {
	rows, err := q.db.Query(ctx, getFlatsForHouse, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFlatsForHouseRow
	for rows.Next() {
		var i GetFlatsForHouseRow
		if err := rows.Scan(
			&i.Flat.FlatID,
			&i.Flat.FlatNumber,
			&i.Flat.HouseID,
			&i.Flat.Area,
			&i.Resident.ResidentID,
			&i.Resident.FlatID,
			&i.Resident.PhoneNumber,
			&i.Resident.Fio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFlat = `-- name: InsertFlat :one
insert into flat(flat_number, house_id, area)
values ($1, $2, $3)
RETURNING flat_id, flat_number, house_id, area
`

type InsertFlatParams struct {
	FlatNumber int32
	HouseID    uuid.UUID
	Area       int32
}

func (q *Queries) InsertFlat(ctx context.Context, arg InsertFlatParams) (Flat, error) {
	row := q.db.QueryRow(ctx, insertFlat, arg.FlatNumber, arg.HouseID, arg.Area)
	var i Flat
	err := row.Scan(
		&i.FlatID,
		&i.FlatNumber,
		&i.HouseID,
		&i.Area,
	)
	return i, err
}
