// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: flat.sql

package database

import (
	"github.com/google/uuid"
)

type CreateFlatsParams struct {
	FlatNumber int32
	HouseID    uuid.UUID
}
