// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: house.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHouse = `-- name: CreateHouse :one
INSERT INTO house(address)
values($1)
RETURNING house_id, address
`

func (q *Queries) CreateHouse(ctx context.Context, address pgtype.Text) (House, error) {
	row := q.db.QueryRow(ctx, createHouse, address)
	var i House
	err := row.Scan(&i.HouseID, &i.Address)
	return i, err
}
