// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Flat struct {
	FlatID  uuid.UUID
	Address pgtype.Text
	HouseID uuid.UUID
}

type House struct {
	HouseID uuid.UUID
	Address pgtype.Text
}
