// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID uuid.UUID
	Balance   decimal.Decimal
	Code      int32
	Name      string
}

type Flat struct {
	FlatID     uuid.UUID
	FlatNumber int32
	HouseID    uuid.UUID
	Area       int32
}

type FlatAccount struct {
	FlatAccountID uuid.UUID
	FlatID        uuid.UUID
	AccountID     uuid.UUID
}

type FlatOwner struct {
	FlatOwnerID uuid.UUID
	FlatID      uuid.UUID
	ResidentID  uuid.UUID
}

type House struct {
	HouseID uuid.UUID
	Address string
}

type Payment struct {
	PaymentID uuid.UUID
	AccountID uuid.UUID
	Amount    decimal.Decimal
	Note      pgtype.Text
}

type PaymentPlan struct {
	PaymentPlanID uuid.UUID
	HouseID       uuid.UUID
	PeriodID      uuid.UUID
	DateFrom      pgtype.Timestamp
	DateTo        pgtype.Timestamp
	MonthlyAmount decimal.Decimal
}

type Period struct {
	PeriodID uuid.UUID
	Period   string
}

type Resident struct {
	ResidentID  uuid.UUID
	FlatID      uuid.UUID
	PhoneNumber string
	Fio         string
}
