// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_plans.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentPlan = `-- name: CreatePaymentPlan :one
INSERT INTO payment_plan(period_id, date_from, date_to, monthly_amount)
VALUES($1, $2, $3, $4)
RETURNING payment_plan_id, house_id, period_id, date_from, date_to, monthly_amount
`

type CreatePaymentPlanParams struct {
	PeriodID      uuid.UUID
	DateFrom      pgtype.Timestamp
	DateTo        pgtype.Timestamp
	MonthlyAmount decimal.Decimal
}

func (q *Queries) CreatePaymentPlan(ctx context.Context, arg CreatePaymentPlanParams) (PaymentPlan, error) {
	row := q.db.QueryRow(ctx, createPaymentPlan,
		arg.PeriodID,
		arg.DateFrom,
		arg.DateTo,
		arg.MonthlyAmount,
	)
	var i PaymentPlan
	err := row.Scan(
		&i.PaymentPlanID,
		&i.HouseID,
		&i.PeriodID,
		&i.DateFrom,
		&i.DateTo,
		&i.MonthlyAmount,
	)
	return i, err
}

const getLatestPaymentPlanByHouseID = `-- name: GetLatestPaymentPlanByHouseID :one
SELECT payment_plan_id, house_id, period_id, date_from, date_to, monthly_amount FROM payment_plan
WHERE house_id = $1
AND date_to IS NULL
`

func (q *Queries) GetLatestPaymentPlanByHouseID(ctx context.Context, houseID uuid.UUID) (PaymentPlan, error) {
	row := q.db.QueryRow(ctx, getLatestPaymentPlanByHouseID, houseID)
	var i PaymentPlan
	err := row.Scan(
		&i.PaymentPlanID,
		&i.HouseID,
		&i.PeriodID,
		&i.DateFrom,
		&i.DateTo,
		&i.MonthlyAmount,
	)
	return i, err
}

const getPaymentPlansByHouseID = `-- name: GetPaymentPlansByHouseID :many
SELECT payment_plan_id, house_id, period_id, date_from, date_to, monthly_amount FROM payment_plan
where house_id = $1
`

func (q *Queries) GetPaymentPlansByHouseID(ctx context.Context, houseID uuid.UUID) ([]PaymentPlan, error) {
	rows, err := q.db.Query(ctx, getPaymentPlansByHouseID, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentPlan
	for rows.Next() {
		var i PaymentPlan
		if err := rows.Scan(
			&i.PaymentPlanID,
			&i.HouseID,
			&i.PeriodID,
			&i.DateFrom,
			&i.DateTo,
			&i.MonthlyAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
