// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resident.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertResident = `-- name: InsertResident :one
INSERT INTO resident(flat_id, phone_number, fio)
VALUES($1, $2, $3)
RETURNING resident_id, flat_id, phone_number, fio
`

type InsertResidentParams struct {
	FlatID      uuid.UUID
	PhoneNumber string
	Fio         string
}

func (q *Queries) InsertResident(ctx context.Context, arg InsertResidentParams) (Resident, error) {
	row := q.db.QueryRow(ctx, insertResident, arg.FlatID, arg.PhoneNumber, arg.Fio)
	var i Resident
	err := row.Scan(
		&i.ResidentID,
		&i.FlatID,
		&i.PhoneNumber,
		&i.Fio,
	)
	return i, err
}
