// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package themecontroller

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Script() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script defer>\n  (() => {\n\n    const darkTheme = JSON.parse(localStorage.getItem(\"theme\"))\n    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;\n\n    if (darkTheme !== null) {\n      document.getElementById(\"theme-controller\").checked = darkTheme;\n\n      console.log(\"darkTheme: \", darkTheme)\n      document.documentElement.setAttribute(\"data-theme\", darkTheme ? \"dark\" : \"light\");\n      window.theme = darkTheme;\n      console.log(\"darkTheme is not null\")\n      console.log(\"new theme: \", darkTheme ? \"dark\" : \"light\");\n    } else {\n      document.getElementById(\"theme-controller\").checked = prefersDark;\n      document.documentElement.setAttribute(\"data-theme\", prefersDark ? \"dark\" : \"light\");\n      window.theme = prefersDark;\n      console.log(\"darkTheme is  null\")\n    }\n\n\n    // document.getElementById(\"theme-controller\").checked = window.theme;\n    // document.documentElement.setAttribute(\"data-theme\", window.theme ? \"dark\" : \"light\");\n\n    localStorage.setItem(\"theme\", window.theme);\n\n    document.getElementById(\"theme-controller\").addEventListener(\"change\", e => {\n      console.log(e.target.checked);\n      // e.target.checked = !e.target.checked;\n      document.documentElement.setAttribute(\"data-theme\", e.target.checked ? \"dark\" : \"light\");\n      window.theme = e.target.checked;\n\n      localStorage.setItem(\"theme\", window.theme);\n    });\n  })()\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// x-init="
// $watch('state', value => {
// localStorage.setItem(key, JSON.stringify(value));
// document.documentElement.setAttribute('data-theme', state ? 'dark' : 'light');
// })
// "
func ThemeController() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div x-data=\"{\n    state: window.theme,\n    key: 'theme',\n  }\" class=\"navbar-end\"><label class=\"flex cursor-pointer gap-2\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"5\"></circle> <path d=\"M12 1v2M12 21v2M4.2 4.2l1.4 1.4M18.4 18.4l1.4 1.4M1 12h2M21 12h2M4.2 19.8l1.4-1.4M18.4 5.6l1.4-1.4\"></path></svg> <input type=\"checkbox\" value=\"dark\" class=\"toggle\n        bg-primary-content\n        theme-controller\" x-model=\"state\" id=\"theme-controller\"> <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z\"></path></svg></label></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
